### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
# print gli elementi della mia lista
my_liste_cifra= [0,1,2,3,4,5,6,7,8,9] 
for i in my_liste_cifra:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#con la list comprehension
my_liste_cifra= [0,1,2,3,4,5,6,7,8,9]
modulo_risult=[i % 2 for i in my_liste_cifra]
print(modulo_risult)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [95]:
# print gli elementi della mia lista nell'intervallo [0:7]
my_liste_cifra= [0,1,2,3,4,5,6,7,8,9]
# for i in range(7):
    
#  print(i)
 #con la list comprehension
num_list = [x for x in my_liste_cifra if x in range(7)]
print(num_list) 


[0, 1, 2, 3, 4, 5, 6]


In [ ]:
my_liste_cifra= [0,1,2,3,4,5,6,7,8,9]
somma = lambda i:sum(my_liste_cifra)
somma
risultato=somma(i)
print(risultato)
# somme = sum(my_liste_cifra)
# somme

45

In [31]:
my_liste_cifra= ['0','1','2','3','4','5','6','7','8','9','a']
for i in my_liste_cifra:
    if i=='a' :
        print (i)

a


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
# 1) crea un vettore contenente tutti i numeri primi compresi tra 0 e 10.
# funzione di verificazione che i sia un numero primo.
def primo(i):
    if i<2:
        return False
    for j in range(2,int(i ** 0.5)+1):
     if i % j == 0 :
        return False
    else :
     return True
# con la list comprehension uso la funzione primo per creare il mio vettore.       
num_primi = [i for i in range(11) if primo(i) ]
print(num_primi) # stampo tutti i numeri primi tra 0 a 10.



[2, 3, 5, 7]


In [130]:
#2) e 3) 
# numero_totale_num_primi = len(num_primi)
# numero_totale_num_primi
import numpy as np
num_primi = np.array([2,3,5,7], dtype =int)
print(num_primi.size)
# n = len(range(0,10))
# n

4


In [133]:
#4) Scrivo l'array usando una list comprehension che controlla che i numeri siano primi.
import numpy as np

num_primi = np.array([i for i in range(11) if i >= 2 and all(i % j !=0 for j in range(2, int(i**0.5)+1))])
print(num_primi)



[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [157]:
# crea un array a
import numpy as np
a=np.array([1,2,3,4])
b= np.array([1,"erica",2,3,])
c= a[::-1] # slicing inverse la liste
print(a)
print(b)
print(c)
#diviso larray a per larray c
d=a/c
print(d)


[1 2 3 4]
['1' 'erica' '2' '3']
[4 3 2 1]
[0.25       0.66666667 1.5        4.        ]
