In [ ]:
### **1. Indicizzazione booleana**

# 1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.
import numpy as np
vett_num_primi = np.array([x for x in range(2,21) if all(x%i!=0 for i in range(2, int(x**0.5) +1))])
vett_num_primi
# another possibility
numeri_primi = [x for x in range(2,21) if all(x%i!=0 for i in range(2, int(x**0.5)+1))]
numeri_primi

# 2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.
vett_num_primi>10
voci_maggiori10 =vett_num_primi[vett_num_primi>10]
voci_maggiori10

#3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista. 
numeri_pari_lista =[x for x in numeri_primi if x%2==0]
numeri_pari_lista

[2]

In [67]:
### **2.  Operazioni su array**
# Crea un array **a**, 2D (senza digitarlo esplicitamente)
import random
import numpy as np
a = np.arange(20).reshape((4,5))

# Genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.
b =a[[1,3],:] 
c = a[2, :] 
# Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.
d= a/c
a, b, c , d

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]]),
 array([10, 11, 12, 13, 14]),
 array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
        [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.5       , 1.45454545, 1.41666667, 1.38461538, 1.35714286]]))

In [ ]:
### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
# Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
import random
import numpy as np
a1= np.random.rand(10,3)
a1
#Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.
#  Distanza assoluta a 0.5
distanza= np.abs(a1 - 0.5)

# Indice della valeure minimale (più vicino ) per linea
indici = np.argmin(distanza, axis=1)

# Estrare i valori con fancy indexing
valori_vicini = a1[np.arange(10), indici]
distanza , indici , valori_vicini



(array([[0.04093263, 0.04025911, 0.25045565],
        [0.24146149, 0.10607221, 0.07100906],
        [0.01855263, 0.48207167, 0.11252712],
        [0.05803745, 0.43564042, 0.19372642],
        [0.46021001, 0.49301432, 0.15258553],
        [0.08403496, 0.40755089, 0.49981571],
        [0.45003131, 0.23186604, 0.01952614],
        [0.13092438, 0.3400934 , 0.01627636],
        [0.09612806, 0.39213256, 0.36212506],
        [0.06689416, 0.36439934, 0.247184  ]]),
 array([1, 2, 0, 0, 2, 0, 2, 2, 0, 0]),
 array([0.54025911, 0.42899094, 0.48144737, 0.55803745, 0.65258553,
        0.41596504, 0.48047386, 0.51627636, 0.40387194, 0.43310584]))

In [138]:
### **4. Analisi della Frequenza Cardiaca con NumPy**

# 1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata: `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
# Inserisci questi valori in un array NumPy.

import numpy as np
freq_cardiaca = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
freq_cardiaca

# 2. **Trova la frequenza cardiaca minima** registrata durante la giornata. 

freq_minima = np.min(freq_cardiaca)
freq_minima
# Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.

# 3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
freq_max= np.max(freq_cardiaca)
freq_max
# Questo valore è un'indicazione dell'intensità dell'esercizio fisico.

# 4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**: 
per_lettura_sopra_120 =np.mean(freq_cardiaca>120) * 100
per_lettura_sopra_120

# Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
freq_sup_120 = freq_cardiaca>120
freq_sup_120

# Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.
per_oss_sopra_120 =np.mean(freq_cardiaca>120)*100
per_oss_sopra_120
# ovvero
import pandas as pd
per_oss_sopra_120 = pd.Series(freq_cardiaca).gt(120).mean()*100
per_oss_sopra_120


np.float64(52.38095238095239)

In [ ]:
### **5. Manipolazione di vettori**

# 1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
import numpy as np
stipendi = np.array([50000 , 105250 , 55000 , 89000])
stipendi

# Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?
costo_totale_perso = np.sum(stipendi)
costo_totale_perso

# 2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
# Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.
bonus = (105250*15)/100
bonus

stipendi_modificato1 =np.array([x + bonus if x==105250 else x for x in stipendi])
stipendi_modificato1 

# 3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  

# Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?
# Sì questo valore è presente nel mio array

# 4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.
stipendi_modificato.dtype
stipendi_2 = np.array([x + bonus if x==105250 else x for x in stipendi], dtype=np.float64)
stipendi_2

# 5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
# Modifica il vettore per riflettere questo cambiamento.
bonus1 = (50000*20)/100
bonus1
stipendi_modificato2 = np.array([x + bonus1 if x==np.min(stipendi) else x for x in stipendi_2])
stipendi_modificato2


# 6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
# Modifica il vettore di conseguenza.

stipendi_modificato2[[2, 3]] = np.round(stipendi[[2, 3]] * 1.10, 2)
print(stipendi_modificato2)

# 7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
costo_totale_finale = np.sum(stipendi_modificato2)
costo_totale_finale
# Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?
costo_azienda = costo_totale_finale -costo_totale_perso
costo_azienda # Perchè l'aumento del CEO ha indotto quello degli altri.


[ 60000.  121037.5  60500.   97900. ]


np.float64(40187.5)

In [209]:
### **6. Valori di Co2**

# 1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2
import numpy as np
CO2_csv = np.load('CO2.csv')
CO2_csv
# 2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio
valori_sopra_soglia = np.sum(CO2_csv>18)
valori_sopra_soglia
media_valori_sopra_soglia = np.mean(CO2_csv[CO2_csv>18])
media_valori_sopra_soglia

# 3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)
somma_totale = np.sum(CO2_csv)
somma_totale_sopra_soglia = np.sum(valori_sopra_soglia)
somma_totale_sopra_soglia
frazione_totale = somma_totale_sopra_soglia/somma_totale
frazione_totale

FileNotFoundError: [Errno 2] No such file or directory: 'CO2.csv'