In [ ]:
### **1. Indicizzazione booleana**

# 1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.
import numpy as np
vett_num_primi = np.array([x for x in range(2,21) if all(x%i!=0 for i in range(2, int(x**0.5) +1))])
vett_num_primi
# another possibility
numeri_primi = [x for x in range(2,21) if all(x%i!=0 for i in range(2, int(x**0.5)+1))]
numeri_primi

# 2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.
vett_num_primi>10
voci_maggiori10 =vett_num_primi[vett_num_primi>10]
voci_maggiori10

#3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista. 
numeri_pari_lista =[x for x in numeri_primi if x%2==0]
numeri_pari_lista

[2]

In [67]:
### **2.  Operazioni su array**
# Crea un array **a**, 2D (senza digitarlo esplicitamente)
import random
import numpy as np
a = np.arange(20).reshape((4,5))

# Genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.
b =a[[1,3],:] 
c = a[2, :] 
# Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.
d= a/c
a, b, c , d

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]]),
 array([10, 11, 12, 13, 14]),
 array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
        [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.5       , 1.45454545, 1.41666667, 1.38461538, 1.35714286]]))

In [ ]:
### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
# Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
import random
import numpy as np
a1= np.random.rand(10,3)
a1
#Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.
#  Distanza assoluta a 0.5
distanza= np.abs(a1 - 0.5)

# Indice della valeure minimale (più vicino ) per linea
indici = np.argmin(distanza, axis=1)

# Estrare i valori con fancy indexing
valori_vicini = a1[np.arange(10), indici]
distanza , indici , valori_vicini



(array([[0.04093263, 0.04025911, 0.25045565],
        [0.24146149, 0.10607221, 0.07100906],
        [0.01855263, 0.48207167, 0.11252712],
        [0.05803745, 0.43564042, 0.19372642],
        [0.46021001, 0.49301432, 0.15258553],
        [0.08403496, 0.40755089, 0.49981571],
        [0.45003131, 0.23186604, 0.01952614],
        [0.13092438, 0.3400934 , 0.01627636],
        [0.09612806, 0.39213256, 0.36212506],
        [0.06689416, 0.36439934, 0.247184  ]]),
 array([1, 2, 0, 0, 2, 0, 2, 2, 0, 0]),
 array([0.54025911, 0.42899094, 0.48144737, 0.55803745, 0.65258553,
        0.41596504, 0.48047386, 0.51627636, 0.40387194, 0.43310584]))

In [138]:
### **4. Analisi della Frequenza Cardiaca con NumPy**

# 1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata: `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
# Inserisci questi valori in un array NumPy.

import numpy as np
freq_cardiaca = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
freq_cardiaca

# 2. **Trova la frequenza cardiaca minima** registrata durante la giornata. 

freq_minima = np.min(freq_cardiaca)
freq_minima
# Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.

# 3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
freq_max= np.max(freq_cardiaca)
freq_max
# Questo valore è un'indicazione dell'intensità dell'esercizio fisico.

# 4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**: 
per_lettura_sopra_120 =np.mean(freq_cardiaca>120) * 100
per_lettura_sopra_120

# Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
freq_sup_120 = freq_cardiaca>120
freq_sup_120

# Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.
per_oss_sopra_120 =np.mean(freq_cardiaca>120)*100
per_oss_sopra_120
# ovvero
import pandas as pd
per_oss_sopra_120 = pd.Series(freq_cardiaca).gt(120).mean()*100
per_oss_sopra_120


np.float64(52.38095238095239)

In [ ]:
### **5. Manipolazione di vettori**

# 1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
import numpy as np
stipendi = np.array([50000 , 105250 , 55000 , 89000])
stipendi

# Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?
costo_totale_perso = np.sum(stipendi)
costo_totale_perso

# 2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
# Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.
bonus = (105250*15)/100
bonus

stipendi_modificato1 =np.array([x + bonus if x==105250 else x for x in stipendi])
stipendi_modificato1 

# 3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  

# Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?
# Sì questo valore è presente nel mio array

# 4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.
stipendi_modificato.dtype
stipendi_2 = np.array([x + bonus if x==105250 else x for x in stipendi], dtype=np.float64)
stipendi_2

# 5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
# Modifica il vettore per riflettere questo cambiamento.
bonus1 = (50000*20)/100
bonus1
stipendi_modificato2 = np.array([x + bonus1 if x==np.min(stipendi) else x for x in stipendi_2])
stipendi_modificato2


# 6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
# Modifica il vettore di conseguenza.

stipendi_modificato2[[2, 3]] = np.round(stipendi[[2, 3]] * 1.10, 2)
print(stipendi_modificato2)

# 7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
costo_totale_finale = np.sum(stipendi_modificato2)
costo_totale_finale
# Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?
costo_azienda = costo_totale_finale -costo_totale_perso
costo_azienda # Perchè l'aumento del CEO ha indotto quello degli altri.


[ 60000.  121037.5  60500.   97900. ]


np.float64(40187.5)

In [210]:
### **6. Valori di Co2**

# 1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2
import numpy as np
CO2_csv = np.load('CO2.csv')
CO2_csv
# 2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio
valori_sopra_soglia = np.sum(CO2_csv>18)
valori_sopra_soglia
media_valori_sopra_soglia = np.mean(CO2_csv[CO2_csv>18])
media_valori_sopra_soglia

# 3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)
somma_totale = np.sum(CO2_csv)
somma_totale_sopra_soglia = np.sum(valori_sopra_soglia)
somma_totale_sopra_soglia
frazione_totale = somma_totale_sopra_soglia/somma_totale
frazione_totale

FileNotFoundError: [Errno 2] No such file or directory: 'CO2.csv'

In [ ]:
 ### **7. Analisi di una matrice**
# Data la matrice survey con età, reddito e anni di istruzione
import numpy as np

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])
survey_matrix

# 1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.
survey_matrix[:,2]>=12
intervistati_almeno_12anni = survey_matrix[survey_matrix[:,2]>=12]
intervistati_almeno_12anni
# 2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.
#redditi_intervistati_almeno_12anni = intervistati_almeno_12anni[:,1]
#redditi_intervistati_almeno_12anni

intervistati_almeno_12anni[:,1] # in un'unica  riga
# 3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.
np.mean(redditi_intervistati_almeno_12anni) # in un'unica riga
#redditoMedio_intervistati_almeno_12anni = np.mean(intervistati_almeno_12anni[:,1])
#redditoMedio_intervistati_almeno_12anni


np.float64(57666.666666666664)

In [ ]:
### **8. Rimpiazzare gli outliers**
import numpy as np

# Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**. 

# La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

# Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

# Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.



nan

In [278]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
ages
ages!=999
ages_filtrato = ages[(ages!=999) & ~np.isnan(ages)]
ages_filtrato
len(ages_filtrato) 
len(ages)
len(ages) - len(ages_filtrato) ## 14 dati errati

14

In [328]:
### 9.**Generazione random di storie**

lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]
lista_parole

# Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  
import random
import numpy as np
#lista_5parole =(lista_parole[1:7]) # codice non casuale, esplicite
#lista_5parole
parole_estratte = random.choices(lista_parole,k=5)
parole_estratte

# Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:
parole_inserite = iter(lista_5parole) # vrea un'iterazione per consumare le parole in ordine
parole_inserite

# Frasi con placeholder
storia = (
    f"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parole_estratte[0]} che proteggeva. "
    f"Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il {parole_estratte[1]} come dono, "
    f"i suoi occhi si spalancarono e lei esclamò una sola parola, '{parole_estratte[2]}'. "
    f"Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole_estratte[3]}. "
    f"Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. "
    f"Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "
    f"'Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole_estratte[4]}!' Ci fu grande gioia e celebrazione."
)

print("Parole estratte:", parole_estratte)
print("\nStoria generata:\n")
print(storia)
#frase_completa = frase.replace('_', '{}').format(*parole_estratte)

Parole estratte: ['SEPARAZIONE', 'AGENTE DI POLIZIA', 'PRESTAZIONE', 'RECUPERO', 'PENALITÀ']

Storia generata:

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico SEPARAZIONE che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il AGENTE DI POLIZIA come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, 'PRESTAZIONE'. Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un RECUPERO. Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 'Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza PENALITÀ!' Ci fu grande gioia e celebrazione.
